### ISSUE TITLE
Cmake error : catkin build and catkin_make

### ISSUE THREAD

**Issue by dinnno** [justagist/franka_ros_interface#13]
Hello, I am a student who is studying grasping with franka panda. 
I'm trying to install the Franka_ros_interface package because I think it will complement our franka panda. The src file in my ros workspace(catkin_ws) contains the package of Franka_ros 0.6.0, libfranka, and the Franka_description in the Franka_ros package. 
so I did modify all occurences franka_panda_description with franka_description. But I get an error at franka_ros_interface/franka_interface/CMakeLists.txt 
Why can't I do catkin_make when I think I installed basic defendencies well?

Any advice or help is appreciated.
Thanks you a lot !

**Comment by alish212** [comment]
I also have a question on how to build the workspaces properly. Should we build this package in the same folder as native franka_ros library or building in different workspaces is fine?

**Comment by justagist** [comment]
> But I get an error at franka_ros_interface/franka_interface/CMakeLists.txt
@dinnno What is the error message that you get?

**Comment by justagist** [comment]
> I also have a question on how to build the workspaces properly. Should we build this package in the same folder as native franka_ros library or building in different workspaces is fine?

It is easier to build everything in the same workspace, but having multiple workspaces is fine as long as they are [properly overlaid](http://wiki.ros.org/catkin/Tutorials/workspace_overlaying).

**Comment by dinnno** [comment]
@justagist thank you for your answer:)
The error code is very long, so i've been coping some of them !


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/opt/ros/melodic/lib/libfranka.so.0.8.0" to
  target "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/opt/ros/melodic/lib/liburdf.so" to target
  "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/liburdfdom_sensor.so" to target
  "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/liburdfdom_model_state.so" to target
  "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/liburdfdom_model.so"
  to target "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/liburdfdom_world.so"
  to target "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libtinyxml.so" to
  target "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/opt/ros/melodic/lib/librosconsole_bridge.so"
  to target "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/opt/ros/melodic/lib/libclass_loader.so" to
  target "franka_control_node" which is not built in this directory.


CMake Error at franka_ros_interface/franka_interface/CMakeLists.txt:80 (target_link_libraries):
  Attempt to add link library "/usr/lib/libPocoFoundation.so" to target
  "franka_control_node" which is not built in this directory.

**Comment by justagist** [comment]
This looks like there is conflict of target file names because they have the same name. I will fix this soon.
Also make sure you are using the release version of the franka_ros package (`git checkout 49e5ac1055e332581b4520a1bd9ac8aaf4580fb1` for melodic branch of franka_ros).

**Comment by justagist** [comment]
Please try again now with the latest version justagist/franka_ros_interface@0983791. Make sure you use the proper version of franka_ros as well.

**Comment by dinnno** [comment]
@justagist thank you a lot !!!
