### ISSUE TITLE
RLException:ERROR : cloud not contact master [http://172.27.183.229:11311]

### ISSUE THREAD

**Issue by dinnno** [justagist/franka_ros_interface#14]
Hello, I am a student who study using franka panda robot
I am building and using  your package well. 
but, when  i tried to use ./franka.sh master in robot computer, I got an error

actually, i did set up ./franka.sh file well as following your documentary.
It is revised franka.sh file 

## ========================================= #

# ----- EDIT THIS TO MATCH THE IP OF THE FRANKA ROBOT CONTROLLER IN THE NETWORK
FRANKA_ROBOT_IP="172.27.183.230"

# ----- EDIT THIS TO MATCH YOUR IP IN THE NETWORK
your_ip="172.27.183.229"

# ----- EDIT THIS TO MATCH THE IP OF THE MAIN ROS MASTER PC (CONNECTED TO THE FRANKA CONTROLLER)
ROS_MASTER_IP="http://localhost:11311/"

ros_version="melodic"

## ========================================= #

It is part of the contents of the terminal.

NODES
  /
    base_to_link0 (tf/static_transform_publisher)
    controllers (controller_manager/spawner)
    demo_scene_loader (franka_moveit/create_demo_planning_scene.py)
    franka_control (franka_interface/custom_franka_control_node)
    franka_gripper (franka_gripper/franka_gripper_node)
    joint_state_desired_publisher (joint_state_publisher/joint_state_publisher)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    load_controllers (controller_manager/controller_manager)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    state_controller_spawner (controller_manager/spawner)
    world_to_base (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [10444]
RLException: ERROR: could not contact master [http://172.27.183.229:11311]
The traceback for the exception was written to the log file
[master] killing on exit

 The odd thing is, I got a lot of ros node list you made, but soon the connection is automatically shut down.

I will wait your answer. Have a nice day and thank you a lot

**Comment by justagist** [comment]
This is not an issue with the package. It seems the IP is not set for ROS properly. Make sure you set the right IP of your machine for the `your_ip` variable in the file. Also try setting the same value for `ROS_MASTER_IP`. Then run `./franka.sh master` and try again.
To make sure the variables are configured correctly, you can try running `roscore` command. If it is running properly, you should also be able to launch the franka_ros_interface driver node without issue.
