### ISSUE TITLE
Cmake error franka_control

### ISSUE THREAD

**Issue by vincentmaye** [justagist/franka_ros_interface#18]
Hi,
I am trying to build your package but run into the following issue when executing `catkin build franka_ros_interface` :

![image](https://user-images.githubusercontent.com/50368404/98878703-ecf92a00-2483-11eb-9d6e-98f6e2cc7079.png)

It looks like it is unable to locate parts of the franka_ros package which I installed earlier. Also running `roslaunch franka_control franka_control.launch` is working, indicating to me that the package should be accessible.
I appreciate any hints, thanks.

**Comment by justagist** [comment]
Hi,
As mentioned in the readme, Franka ROS Interface requires franka_ros v0.6.0, which means at the moment you will have to build franka_ros from source (the packaged release version for Ubuntu was recently upgraded as well) and build version 0.6.0 of franka_ros (`git checkout 49e5ac1` from the cloned franka_ros github repo).
I will be working on a corresponding update for Franka ROS Interface soon, and hope to publish it soon.

- Saif

**Comment by vincentmaye** [comment]
Thank you very much for clarifying Saif!

**Comment by justagist** [comment]
Hi,
The package should now work with the latest release of franka_ros as well (see ['v0.7.1'](https://github.com/justagist/franka_ros_interface/tree/v0.7.1) branch). But it is not fully tested yet!

- Saif
