### ISSUE TITLE
camke error: can't find franka_hw

### ISSUE THREAD

**Issue by saprrow** [justagist/franka_ros_interface#20]
Hi, 
I am trying to build your package but run into the following issue when executing `catkin build franka_ros_interface`:
![Screenshot from 2021-01-20 18-40-59](https://user-images.githubusercontent.com/44662300/105164326-f5d73d80-5b4f-11eb-8541-5117eedee668.png)

I built libfranka and frankros from source. It looks like the cmakefile can't find the franka_hw built in frank_ros.
So how to make the franka_ros_interface find the franka_hw path?
Thanks for your help!
Thanks!

**Comment by justagist** [comment]
Hi,
Make sure you use the compatible versions of libfranka, franka_ros and franka_ros_interface as mentioned in the README.
See #19.

- Saif

**Comment by saprrow** [comment]
Thanks!!!
I forgot the issue I just posted. HHHH~
