### ISSUE TITLE
I got a Problem with the arm controller

### ISSUE THREAD

**Issue by mo4jamal** [justagist/franka_ros_interface#24]
When I launch the moveit demo and want to execute an arm movement, I receive the following error:

[ERROR] [1616651255.407653286]: Unable to identify any set of controllers that can actuate the specified joints: [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
[ERROR] [1616651255.407667569]: Known controllers and their joints:
controller 'franka_gripper' controls joints:
  panda_finger_joint1
  panda_finger_joint2

There is no problem with executing a hand movement and the franka-ros and also the libfranka demos are working fine.
The panda robot is on firmware 4.0.4. libfranka on 0.8.0 and franka-ros on 0.7.1

**Comment by mo4jamal** [comment]
while launching the interface, I noticed that the position_joint_trajectory_controller/follow_joint_trajectory is not connected.

[ERROR] [1616654245.872824741]: Action client not connected: position_joint_trajectory_controller/follow_joint_trajectory

how do I connect it?

**Comment by justagist** [comment]
You might be missing the joint-trajectory-controller package. Try running the launch file after `apt install ros-melodic-joint-trajectory-controller`.

**Comment by mo4jamal** [comment]
Is working now, thank you!
