### ISSUE TITLE
[franka_control-2] has died! please help

### ISSUE THREAD

**Issue by Sission** [justagist/franka_ros_interface#25]
Hi! I suffered the following error when I run
$ roslaunch franka_interface interface.launch

**Ubuntu 16.04, Kinetic.
I was running as the "master"
$ ./franka.sh master**

**By the way, I can control the real robot by using panda_moveit_config moveit_rviz.launch**

**Here is the error**

REQUIRED process [franka_control-2] has died!
process has died [pid 27696, exit code -6, cmd /home/sission/ws_moveit/devel/lib/franka_interface/custom_franka_control_node __name:=franka_control __log:=/home/sission/.ros/log/65158e3c-8e7b-11eb-8b22-000c2918a907/franka_control-2.log].
log file: /home/sission/.ros/log/65158e3c-8e7b-11eb-8b22-000c2918a907/franka_control-2*.log
Initiating shutdown!

----------FULL LOG--------------
roslaunch franka_interface interface.launch load_gripper:=false
... logging to /home/sission/.ros/log/65158e3c-8e7b-11eb-8b22-000c2918a907/roslaunch-Ubuntu16-27648.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.126.9:33143/

SUMMARY
========

PARAMETERS
 * /controllers_config/command_timeout: 0.2
 * /controllers_config/default_controller: position_joint_tr...
 * /controllers_config/impedance_controller: franka_ros_interf...
 * /controllers_config/position_controller: franka_ros_interf...
 * /controllers_config/torque_controller: franka_ros_interf...
 * /controllers_config/trajectory_controller: position_joint_tr...
 * /controllers_config/velocity_controller: franka_ros_interf...
 * /franka_control/publish_frequency: 1000
 * /franka_control/robot_ip: 192.168.126.3
 * /franka_ros_interface/custom_franka_state_controller/arm_id: panda
 * /franka_ros_interface/custom_franka_state_controller/joint_names: ['panda_joint1', ...
 * /franka_ros_interface/custom_franka_state_controller/publish_rate: 1000
 * /franka_ros_interface/custom_franka_state_controller/type: franka_interface/...
 * /franka_ros_interface/effort_joint_impedance_controller/arm_id: panda
 * /franka_ros_interface/effort_joint_impedance_controller/coriolis_factor: 1.0
 * /franka_ros_interface/effort_joint_impedance_controller/d_gains: [50.0, 50.0, 50.0...
 * /franka_ros_interface/effort_joint_impedance_controller/joint_names: ['panda_joint1', ...
 * /franka_ros_interface/effort_joint_impedance_controller/k_gains: [1200.0, 1000.0, ...
 * /franka_ros_interface/effort_joint_impedance_controller/publish_rate: 30.0
 * /franka_ros_interface/effort_joint_impedance_controller/type: franka_ros_contro...
 * /franka_ros_interface/effort_joint_position_controller/arm_id: panda
 * /franka_ros_interface/effort_joint_position_controller/d_gains: [50.0, 50.0, 50.0...
 * /franka_ros_interface/effort_joint_position_controller/joint_names: ['panda_joint1', ...
 * /franka_ros_interface/effort_joint_position_controller/k_gains: [1200.0, 1000.0, ...
 * /franka_ros_interface/effort_joint_position_controller/publish_rate: 30.0
 * /franka_ros_interface/effort_joint_position_controller/type: franka_ros_contro...
 * /franka_ros_interface/effort_joint_torque_controller/arm_id: panda
 * /franka_ros_interface/effort_joint_torque_controller/compensate_coriolis: False
 * /franka_ros_interface/effort_joint_torque_controller/joint_names: ['panda_joint1', ...
 * /franka_ros_interface/effort_joint_torque_controller/type: franka_ros_contro...
 * /franka_ros_interface/position_joint_position_controller/joint_names: ['panda_joint1', ...
 * /franka_ros_interface/position_joint_position_controller/type: franka_ros_contro...
 * /franka_ros_interface/velocity_joint_velocity_controller/joint_names: ['panda_joint1', ...
 * /franka_ros_interface/velocity_joint_velocity_controller/type: franka_ros_contro...
 * /gripper_config/default_grasp_epsilon/inner: 0.005
 * /gripper_config/default_grasp_epsilon/outer: 0.005
 * /gripper_config/default_speed: 0.1
 * /gripper_config/joint_names: ['panda_finger_jo...
 * /joint_state_desired_publisher/rate: 1000
 * /joint_state_desired_publisher/source_list: ['franka_ros_inte...
 * /joint_state_publisher/rate: 1000
 * /joint_state_publisher/source_list: ['franka_ros_inte...
 * /move_group/allow_trajectory_execution: True
 * /move_group/controller_list: [{'default': True...
 * /move_group/hand/planner_configs: ['SBLkConfigDefau...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_frame: camera_rgb_optica...
 * /move_group/octomap_resolution: 0.05
 * /move_group/panda_arm/planner_configs: ['SBLkConfigDefau...
 * /move_group/panda_arm_hand/planner_configs: ['SBLkConfigDefau...
 * /move_group/planner_configs/BFMTkConfigDefault/balanced: 0
 * /move_group/planner_configs/BFMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/BFMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/BFMTkConfigDefault/heuristics: 1
 * /move_group/planner_configs/BFMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/BFMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/BFMTkConfigDefault/optimality: 1
 * /move_group/planner_configs/BFMTkConfigDefault/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMTkConfigDefault/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/BiESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiESTkConfigDefault/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRTkConfigDefault/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/init_temperature: 100
 * /move_group/planner_configs/BiTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/type: geometric::BiTRRT
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/FMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/FMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/FMTkConfigDefault/heuristics: 0
 * /move_group/planner_configs/FMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/FMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/FMTkConfigDefault/radius_multiplier: 1.1
 * /move_group/planner_configs/FMTkConfigDefault/type: geometric::FMT
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRTkConfigDefault/epsilon: 0.4
 * /move_group/planner_configs/LBTRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBTRRTkConfigDefault/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRMkConfigDefault/range: 0.0
 * /move_group/planner_configs/LazyPRMkConfigDefault/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstarkConfigDefault/type: geometric::LazyPR...
 * /move_group/planner_configs/PDSTkConfigDefault/type: geometric::PDST
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/ProjESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ProjESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ProjESTkConfigDefault/type: geometric::ProjEST
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/SPARSkConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARSkConfigDefault/max_failures: 1000
 * /move_group/planner_configs/SPARSkConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARSkConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARSkConfigDefault/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwokConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwokConfigDefault/max_failures: 5000
 * /move_group/planner_configs/SPARStwokConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwokConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwokConfigDefault/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDEkConfigDefault/degree: 16
 * /move_group/planner_configs/STRIDEkConfigDefault/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/STRIDEkConfigDefault/max_degree: 18
 * /move_group/planner_configs/STRIDEkConfigDefault/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDEkConfigDefault/min_degree: 12
 * /move_group/planner_configs/STRIDEkConfigDefault/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDEkConfigDefault/range: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDEkConfigDefault/use_projected_distance: 0
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planner_configs/TrajOptDefault/type: geometric::TrajOpt
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{'point_subsampl...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/allowed_start_tolerance: 0.01
 * /position_joint_trajectory_controller/constraints/goal_time: 0.5
 * /position_joint_trajectory_controller/constraints/panda_joint1/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint2/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint3/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint4/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint5/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint6/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint7/goal: 0.05
 * /position_joint_trajectory_controller/joints: ['panda_joint1', ...
 * /position_joint_trajectory_controller/type: position_controll...
 * /robot_config/arm_id: panda
 * /robot_config/cutoff_frequency: 100
 * /robot_config/internal_controller: joint_impedance
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint1: 15.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint2: 7.5
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint3: 10.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint4: 12.5
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint5: 15.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint6: 20.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint7: 20.0
 * /robot_config/joint_config/joint_effort_limit/panda_joint1: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint2: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint3: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint4: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint5: 12
 * /robot_config/joint_config/joint_effort_limit/panda_joint6: 12
 * /robot_config/joint_config/joint_effort_limit/panda_joint7: 12
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint1: -2.8973
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint2: -1.7628
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint3: -2.8973
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint4: -3.0718
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint5: -2.8973
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint6: -0.0175
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint7: -2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint1: 2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint2: 1.7628
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint3: 2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint4: -0.0698
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint5: 2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint6: 3.7525
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint7: 2.8973
 * /robot_config/joint_config/joint_velocity_limit/panda_joint1: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint2: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint3: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint4: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint5: 2.61
 * /robot_config/joint_config/joint_velocity_limit/panda_joint6: 2.61
 * /robot_config/joint_config/joint_velocity_limit/panda_joint7: 2.61
 * /robot_config/joint_names: ['panda_joint1', ...
 * /robot_config/neutral_pose/panda_joint1: -0.0177920602278
 * /robot_config/neutral_pose/panda_joint2: -0.760123541104
 * /robot_config/neutral_pose/panda_joint3: 0.0197826070234
 * /robot_config/neutral_pose/panda_joint4: -2.34205014054
 * /robot_config/neutral_pose/panda_joint5: 0.0298405313558
 * /robot_config/neutral_pose/panda_joint6: 1.54119352986
 * /robot_config/neutral_pose/panda_joint7: 0.753448658975
 * /robot_config/rate_limiting: True
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/panda_arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/panda_arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/panda_arm/kinematics_solver_timeout: 0.05
 * /robot_description_planning/joint_limits/panda_finger_joint1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/panda_finger_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_finger_joint1/max_acceleration: 0
 * /robot_description_planning/joint_limits/panda_finger_joint1/max_velocity: 0.1
 * /robot_description_planning/joint_limits/panda_finger_joint2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/panda_finger_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_finger_joint2/max_acceleration: 0
 * /robot_description_planning/joint_limits/panda_finger_joint2/max_velocity: 0.1
 * /robot_description_planning/joint_limits/panda_joint1/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint1/max_acceleration: 3.75
 * /robot_description_planning/joint_limits/panda_joint1/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint2/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint2/max_acceleration: 1.875
 * /robot_description_planning/joint_limits/panda_joint2/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint3/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint3/max_acceleration: 2.5
 * /robot_description_planning/joint_limits/panda_joint3/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint4/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint4/max_acceleration: 3.125
 * /robot_description_planning/joint_limits/panda_joint4/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint5/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint5/max_acceleration: 3.75
 * /robot_description_planning/joint_limits/panda_joint5/max_velocity: 2.61
 * /robot_description_planning/joint_limits/panda_joint6/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint6/max_acceleration: 5
 * /robot_description_planning/joint_limits/panda_joint6/max_velocity: 2.61
 * /robot_description_planning/joint_limits/panda_joint7/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint7/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint7/max_acceleration: 5
 * /robot_description_planning/joint_limits/panda_joint7/max_velocity: 2.61
 * /robot_description_semantic: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 1000
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /
    base_to_link0 (tf/static_transform_publisher)
    controllers (controller_manager/spawner)
    demo_scene_loader (franka_moveit/create_demo_planning_scene.py)
    franka_control (franka_interface/custom_franka_control_node)
    joint_state_desired_publisher (joint_state_publisher/joint_state_publisher)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    load_controllers (controller_manager/controller_manager)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    state_controller_spawner (controller_manager/spawner)
    world_to_base (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [27666]
ROS_MASTER_URI=http://192.168.126.9:11311

setting /run_id to 65158e3c-8e7b-11eb-8b22-000c2918a907
process[rosout-1]: started with pid [27679]
started core service [/rosout]
process[franka_control-2]: started with pid [27696]
process[state_controller_spawner-3]: started with pid [27697]
process[robot_state_publisher-4]: started with pid [27703]
process[joint_state_publisher-5]: started with pid [27711]
terminate called after throwing an instance of 'franka::IncompatibleVersionException'
  what():  libfranka: Incompatible library version (server version: 3, library version: 4). Please check https://frankaemika.github.io for Panda system updates or use a different version of libfranka.
process[joint_state_desired_publisher-6]: started with pid [27723]
process[controllers-7]: started with pid [27734]
process[load_controllers-8]: started with pid [27740]
process[base_to_link0-9]: started with pid [27741]
process[world_to_base-10]: started with pid [27756]
process[move_group-11]: started with pid [27762]
process[demo_scene_loader-12]: started with pid [27767]
[ INFO] [1616794620.703314411]: Loading robot model 'panda'...
[ WARN] [1616794620.703414492]: Skipping virtual joint 'virtual_joint' because its child frame 'panda_link0' does not match the URDF frame 'world'
[ INFO] [1616794620.703446625]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1616794620.789231351]: Loading robot model 'panda'...
[ WARN] [1616794620.789315386]: Skipping virtual joint 'virtual_joint' because its child frame 'panda_link0' does not match the URDF frame 'world'
[ INFO] [1616794620.789343735]: No root/virtual joint specified in SRDF. Assuming fixed joint
================================================================================REQUIRED process [franka_control-2] has died!
process has died [pid 27696, exit code -6, cmd /home/sission/ws_moveit/devel/lib/franka_interface/custom_franka_control_node __name:=franka_control __log:=/home/sission/.ros/log/65158e3c-8e7b-11eb-8b22-000c2918a907/franka_control-2.log].
log file: /home/sission/.ros/log/65158e3c-8e7b-11eb-8b22-000c2918a907/franka_control-2*.log
Initiating shutdown!
================================================================================
[ INFO] [1616794620.820620780]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1616794620.824001852]: MoveGroup debug mode is ON
Starting context monitors...
[ INFO] [1616794620.824068831]: Starting scene monitor
[ INFO] [1616794620.827450039]: Listening to '/planning_scene'
[ INFO] [1616794620.827513880]: Starting world geometry monitor
[ INFO] [1616794620.830515661]: Listening to '/collision_object' using message notifier with target frame '/world '
[ INFO] [1616794620.835004460]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1616794620.857181827]: Listening to '/camera/depth_registered/points' using message filter with target frame '/world '
[ INFO] [1616794620.871207186]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[INFO] [1616794620.874708]: Controller Spawner: Waiting for service controller_manager/load_controller
[demo_scene_loader-12] killing on exit
Traceback (most recent call last):
  File "/home/sission/ws_moveit/src/franka_ros_interface/franka_moveit/scripts/create_demo_planning_scene.py", line 31, in <module>
    import moveit_commander
  File "/home/sission/ws_moveit/devel/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 3, in <module>
  File "/home/sission/ws_moveit/src/moveit/moveit_commander/src/moveit_commander/planning_scene_interface.py", line 36, in <module>
    import conversions
  File "/home/sission/ws_moveit/src/moveit/moveit_commander/src/moveit_commander/conversions.py", line 39, in <module>
    import tf
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 39, in <module>
    from .buffer_interface import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 32, in <module>
    import roslib; roslib.load_manifest('tf2_ros')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 171, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 215, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/manifest.py", line 410, in parse_manifest_file
    from rosdep2.rospack import init_rospack_interface, is_ros_package, is_system_dependency, is_view_empty
  File "/usr/lib/python2.7/dist-packages/rosdep2/__init__.py", line 45, in <module>
    from .lookup import RosdepDefinition, RosdepView, RosdepLookup, \
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 44, in <module>
    from .sources_list import SourcesListLoader
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 50, in <module>
    from .gbpdistro_support import get_gbprepo_as_rosdep_data, download_gbpdistro_as_rosdep_data
  File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 18, in <module>
    from .platforms.debian import APT_INSTALLER
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 45, in <module>
    from .pip import PIP_INSTALLER
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/pip.py", line 33, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
[move_group-11] killing on exit
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2955, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 675, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1973, in find_on_path
    lower = entry.lower()
KeyboardInterrupt
[world_to_base-10] killing on exit
[base_to_link0-9] killing on exit
[ INFO] [1616794620.913301995]: Initializing OMPL interface using ROS parameters
[controllers-7] killing on exit
[load_controllers-8] killing on exit
[joint_state_publisher-5] killing on exit
[robot_state_publisher-4] killing on exit
[joint_state_desired_publisher-6] killing on exit
[state_controller_spawner-3] killing on exit
[INFO] [1616794621.064937]: Controller Spawner: Waiting for service controller_manager/load_controller
[WARN] [1616794621.065196]: Controller Spawner couldn't find the expected controller_manager ROS interface.
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/controller_manager", line 48, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/controller_manager/controller_manager_interface.py", line 59, in load_controller
    rospy.wait_for_service('controller_manager/load_controller')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 159, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
[franka_control-2] killing on exit
[WARN] [1616794621.555903]: Controller Spawner couldn't find the expected controller_manager ROS interface.
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...

You can start planning now!

[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by justagist** [comment]
Hi, 
This is not an issue with this package. 
The error clearly says the robot firmware (server) version is not compatible with the libfranka version. Please use compatible versions. This also means you won't be able to run any of the libfranka or franka-ros demos.

**Comment by Sission** [comment]
Thanks! I guess the reason I can run Moveit rviz to control it is that I
don’t use libfranka?

**Comment by justagist** [comment]
Yes, I would think so.
