### ISSUE TITLE
ArmInterface() seems to get stuck moveit '/get_planning_scene'

### ISSUE THREAD

**Issue by gabriellapizzuto** [justagist/franka_ros_interface#32]
Hi,

I would like to test the franka_ros_interface for controlling the joints using torque mode.

Here are some details about my setup:

    ROS noetic
    Python 3.8.10

I have run (with no errors): 

 `roslaunch franka_interface interface.launch load_demo_planning_scene:=false start_moveit:=false  `

However, when I load the ArmInterface, I get the following warnings and it gets stuck here: 

```
[ INFO] [1626184277.199462070]: waitForService: Service [/get_planning_scene] has not been advertised, waiting...
[ WARN] [1626184282.209219557]: service '/get_planning_scene' not advertised yet. Continue waiting...
```

Could you kindly let me know how I could resolve this issue please?

If you need further information I would be happy to provide.

Regards,
Gabriella

**Comment by justagist** [comment]
Hi Gabriella,

> [ INFO] [1626184277.199462070]: waitForService: Service [/get_planning_scene] has not been advertised, waiting...
> [ WARN] [1626184282.209219557]: service '/get_planning_scene' not advertised yet. Continue waiting...

You should not be seeing these messages if you have disabled moveit (`start_moveit:=false`) when launching the interface; instead, the logger should show the following message telling that you won't be able to use any of the MoveIt functionalities in the API: `MoveGroup was not found! This is okay if moveit service is not required!`.

If you had previously started the `interface.launch` with moveit, it is possible that the ROS master was not properly shut down and the ROS parameters still exist in the parameter server. Can you try fully killing any remnant of ROS master and try launching again? (You can test if another ROS master is running by starting `roscore` in another session.)
Please let me know if the problem still persists; I was not able to replicate the issue in the environment you specified (ROS Noetic, Python 3.8.10).

P.S. Not a solution to the problem, but you don't have to disable moveit to be able to perform direct torque control.

Hope this helps.
-- Saif
