### ISSUE TITLE
catkin_make install cant find launch file for franka_ros_controllers

### ISSUE THREAD

**Issue by M-A-Robson** [justagist/franka_ros_interface#6]
franka_ros_interface/franka_ros_controllers/CMakeLists.txt  tries to build a launch directory but there is not launch dir in this package.

I commented out:
install(DIRECTORY launch
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
and that seemed to fix it

**Comment by justagist** [comment]
Thanks for pointing it out. I wouldn't have expected this to cause a build fail, but have made the change in f25f0289fb59e75acdab752dde98f5a2277107ef.
